### ISSUE TITLE
Mekanisme tracking/logging aktifitas user/system

### ISSUE THREAD

**Issue by bcsoetta** [bcsoetta/apishinta#11]
Perlu dibuatkan mekanisme tracking dan log/history di api, terkait siapa melakukan apa dan kapan. Hal ini sudah termuat di tabel :
>**`log`**
>**`status_dok`**

Namun dikarenakan data user (id dan groups atau privilege mengandalkan data dari SSO, maka backend perlu menyimpan data yang setidaknya memuat:
>`access_token` => token akses yang dikirimkan frontend ketika mengakses api (utk endpoints yang memerlukan otentikasi)
>`user_id` => didapat ketika backend mengkonfirmasi `access_token` ke SSO

**Comment by bowvernon110391** [comment]
gk ush pake tabel `token_user_id` dah, krn tiap aktifitas yg perlo dilog kan direquest dengan token jg, ya skalian aja ngelog pake data user brdsrkn token tsb
