### ISSUE TITLE
Relasi dengan kurs valas

### ISSUE THREAD

**Issue by bowvernon110391** [bcsoetta/apishinta#12]
Berhubung data kurs valas/kurs pajak diperlukan untuk perhitungan BM & PDRI, maka perlu dibuat tabel yang dapat mengakomodasi kebutuhan data kurs yang paling tidak memuat informasi sbb:

> 1. kurs bisa berjenis kurs pajak ataupun kurs valas (make sense gk y?)
> 2. jenis datanya adalah rolling table (jadi datanya tidak mereplace data yang sudah ada, cukup menambah di akhir, dan data yang diambil adalah data yang "valid")
> 3. kevalidan data dapat dilihat dari masa berlakunya, tanggal "awal" dan "akhir"
> 4. dengan demikian, ketika data diinput harus dispesifikasikan masa berlakunya (untuk kurs pajak data ini sudah ada di website Badan Kebijakan Fiskal).
> 5. kode valas dan nilai tukarnya paling tidak sampai 4 digit di belakang koma (utk menghandle special case kurs JPY yang bernilai sangat kecil)

**Comment by bowvernon110391** [comment]
Telah dibuat model `Kurs` dan tabel `kurs` dengan elemen sbb

> `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
> `kode_valas` VARCHAR(8) NOT NULL COLLATE 'utf8mb4_unicode_ci',
> `kurs_idr` DECIMAL(18,4) NOT NULL,
> `jenis` ENUM('KURS_PAJAK','KURS_BI') NOT NULL DEFAULT 'KURS_PAJAK' COLLATE 'utf8mb4_unicode_ci',
> `tanggal_awal` DATE NOT NULL,
> `tanggal_akhir` DATE NOT NULL DEFAULT '9999-12-31',
> `created_at` TIMESTAMP NULL DEFAULT NULL,
> `updated_at` TIMESTAMP NULL DEFAULT NULL

Bagaimana tanggapan ente bang @mehuliate ? closenya besok aja klo repot

**Comment by mehuliate** [comment]
kurs BI buat apa y

**Comment by bowvernon110391** [comment]
kurs BI digunakan apabila ada barang yang nilainya tidak menggunakan valuta yang ada di data kurs pajak (misal shekel israel kn gak ada). 
kemaren pas rapat awal pdttnya mnta dsediakan mekanisme utk menginput kurs yg g ad d data kurs pajak
