### ISSUE TITLE
enforce foreign key constraint, use softDeletes

### ISSUE THREAD

**Issue by bcsoetta** [bcsoetta/apishinta#13]
Perlu dijaga integritas data di database (untuk mencegah inconsistent state), maka perlu dilakukan hal-hal sbb:

1. Tegaskan penggunaan foreign key untuk data-data yang memiliki relasi non-polymorphic
2. Gunakan fitur `softDelete` pada laravel, baik di **Model** maupun di **Table Migration** untuk data yang bisa di "hapus"

> Masih ada kompleksitas di mana delete perlu 'cascade', misal
> `cd_header` di "soft" delete, maka `cd_detail` nya jg harus ke "soft" delete
> `cd_header` dihapus maka data turunan (`spmb_header`, `is_header`) jg harus ikut
> `cd_detail` dihapus maka semua data turunan (`spmb_detail`, `is_detail`) jg harus ikut

Untung sudah ada package yg ngebantu hal ini, namanya `askedio/laravel-soft-cascade`

Alternatif lain ya pasang `hooks` / `observer` yang bisa nangkep event ketika Model akan didelete, dan cascading secara manual (klo ini gk ush pake package orang)

3. Gunakan **try-catch transaction block**, di laravel mungkin bentuknya seperti ini:
```
// mulai transaction
DB::transaction();
try {
// manipulasi model di sini
$cd->details()->save($det);
$cd->details()->find(1)->delete();
...dst

// commit di sini, baris di bawah ini sampai ending blok gk akan bsa lnjut klo ada
// error yg ngelempar exception
DB::commit();

// handle sukses di sini...gk akan jalan klo DB::commit ngelempar exception

} catch (\Exception $e) {
// gagal, rollback ke state semula
DB::rollback();
// handle error lebih lanjut di sini...

}
```

Tapi berhubung ini udah agak advanced, mungkin ditunda sampai minimal API untuk CRUD data CD, IS, dan SPMB sudah bisa dicoba.

**Comment by bowvernon110391** [comment]
closed
