### ISSUE TITLE
List endpoints yang sudah dibuat (DOKUMENTASI SEMENTARA)

### ISSUE THREAD

**Issue by bowvernon110391** [bcsoetta/apishinta#16]
**Terkait KURS**
- [x] `GET /kurs` : utk lihat data kurs dengan `pagination` dan `query (tanggal)`. Defaultnya ngasih semua data kurs yg valid per hari ini 15 row per halaman.
- [x] `GET /kurs/23` : utk lihat data kurs dengan `id = 23`
- [x] `GET /kurs/2019-09-01` : utk lihat data kurs valid per `tanggal 2019-09-01` tanpa paginasi (ini yg biasa bakal dipake sama frontend)
- [x] `POST /kurs` `token required:any`: utk insert data kurs dengan format 
> `{kode_valas, kurs_idr, jenis, tanggal_awal, tanggal_akhir}`. Klo sukses dapet `id` dan `uri` dr kurs yg baru diinsert
- [x] `PUT /kurs/2` `token required:any` : utk update data kurs `id = 2` dengan format sesuai pas insert. Ini full replace jd semua datanya kdu komplit
- [x] `DELETE /kurs/3` `token required:CONSOLE` : utk delete data kurs `id = 3`, karena destruktif maka cmn user dengan role `CONSOLE` yang boleh ngapus (mencegah abuse)

**Comment by bowvernon110391** [comment]
**Terkait Penumpang**
- [x] `GET /penumpang`  `token required:any` : lihat data penumpang dengan `pagination` dan `query (q, nama, pekerjaan, nopaspor, kebangsaan)`
- [x] `POST /penumpang` `token required:any` : tambah data penumpang
- [x] `PUT /penumpang` `token required:any` : update/tambah klo gk ada, data penumpang
- [ ] `DELETE /penumpang/3` `token required:CONSOLE` : delete data penumpang. Tp blom dbuat sh. Cmn user CONSOLE yg bsa hapus2.

**Comment by bowvernon110391** [comment]
**Terkait Customs Declaration**
- [x] `GET /dokumen/cd` `token required:any` : liat data customs declaration dengan `pagination` dan `query`. Cuman header, tp ada kolom `jumlah_detail`. 
- [x] `GET /dokumen/cd/3` `token required:any` : liat data CD dengan `id = 3`. Untuk detailnya bisa dilihat dengan
- [x] `GET /dokumen/cd/3/details` `token required:any` : liat data detail CD dengan `id = 3` dalam bentuk `pagination`

- [ ] `POST /dokumen/cd` `token required:PDTT,CONSOLE` : insert data CD (header saja). Perlu role `PDTT` atau `CONSOLE`
- [ ] `PUT /dokumen/cd/3` `token required:PDTT,CONSOLE` : update/create CD (header). Sama kyk di atas, tp perlu locking utk mencegah abuse
- [ ] `POST /dokumen/cd/3/details` `token required:PDTT,CONSOLE` : insert detail CD Baru. 
- [ ] `PUT /dokumen/cd/3/details/2` `token required:PDTT,CONSOLE` : update/create detail CD Baru dgn `id = 2` untuk `cd_header.id = 3`
- [ ] `DELETE /dokumen/cd/3` `token required:CONSOLE` : hapus data CD dengan `id = 3`
- [ ] `DELETE /dokumen/cd/3/details/2` `token required:CONSOLE,PDTT` : hapus data detail CD dengan `id = 2` di `cd_header.id = 3` **DENGAN SYARAT: CD belum terkunci.**  Klo udh terkunci maka gk boleh dihapus, nah utk mekanisme kunci2 nanti kita bicarakan

**Comment by mehuliate** [comment]
**Terkait SSPCP**
- [ ] `GET /dokumen/sspcp` `token required:any` : liat data customs declaration dengan `pagination` dan `query`. Cuman header, tp ada kolom `jumlah_detail`. 
- [ ] `GET /dokumen/sspcp/3` `token required:any` : liat data SPPCP dengan `id = 3`. Untuk detailnya bisa dilihat dengan
- [ ] `GET /dokumen/sspcp/3/details` `token required:any` : liat data detail sspcp dengan `id = 3` dalam bentuk `pagination`

- [ ] `POST /dokumen/sspcp` `token required:PDTT,CONSOLE` : insert data sspcp (header saja). Perlu role `PDTT` atau `CONSOLE`
- [ ] `PUT /dokumen/sspcp/3` `token required:PDTT,CONSOLE` : update/create sspcp (header). Sama kyk di atas, tp perlu locking utk mencegah abuse
- [ ] `POST /dokumen/sspcp/3/details` `token required:PDTT,CONSOLE` : insert detail sspcp Baru. 
- [ ] `PUT /dokumen/sspcp/3/details/2` `token required:PDTT,CONSOLE` : update/create detail sspcp Baru dgn `id = 2` untuk `sspcp_header.id = 3`
- [ ] `DELETE /dokumen/sspcp/3` `token required:CONSOLE` : hapus data sspcp dengan `id = 3`
- [ ] `DELETE /dokumen/sspcp/3/details/2` `token required:CONSOLE,PDTT` : hapus data detail sspcp dengan `id = 2` di `sspcp_header.id = 3` **DENGAN SYARAT: sspcp belum terkunci.**  Klo udh terkunci maka gk boleh dihapus, nah utk mekanisme kunci2 nanti kita bicarakan

- [ ] `PUT /dokumen/sspcp/3/lock` `token required:CONSOLE,PDTT` : ngunci/putus dokumen 
- [ ] `DELETE /dokumen/sspcp/3/lock` `token required:CONSOLE,PDTT` : ngunci/putus dokumen

**Comment by bowvernon110391** [comment]
[ ] /kemasan
[ ] /satuan
[ ] /cd/{id}/details endpoint
[ ] Kalkulasi di SPPBMCP
[V] datepicker wrapper
[V] datatable wrapper
[V] check broker getSessionId()
[V] kapan penomoran?
[V] locking and unlocking mechanism
