### ISSUE TITLE
Pembatalan Dokumen

### ISSUE THREAD

**Issue by bcsoetta** [bcsoetta/apishinta#29]
Perlu dibuat mekanisme pembatalan dokumen dengan spesifikasi sbb:

- REST compliant
- Ada dokumentasi (surat persetujuannya)
- Satu surat pembatalan bisa untuk macam-macam dokumen (bisa > 1)

**Comment by bcsoetta** [comment]
Elemen surat pembatalan:

- Nomor surat
- Tanggal surat
- NIP pejabat
- Keterangan / alasan pembatalan

**Comment by bowvernon110391** [comment]
API proposal:

- `GET /pembatalan` to get all list of pembatalan
- `POST /pembatalan` to record new pembatalan
- `PUT /pembatalan/:pembatalan_id` to update pembatalan of id `pembatalan_id`
- `PUT /pembatalan/:pembatalan_id/:doctype/:docid` to cancel document of type `:doctype` with id of `:docid`
- `DELETE /pembatalan/:pembatalan_id/:pembatalan_detail_id` to cancel cancellation of operation above
- `DELETE /pembatalan/:pembatalan_id` to delete the cancellation
- `PUT /pembatalan/:pembatalan_id/lock` to lock the cancellation so it cannot be used
