### ISSUE TITLE
Model utk Laporan Hasil Pemeriksaan

### ISSUE THREAD

**Issue by bowvernon110391** [bcsoetta/apishinta#32]
Perlu dibuat model `LHP` untuk data model dari LHP. Nantinya bisa dicantumkan di jenis2 dokumen yang butuh pemeriksaan fisik. **(MAKE IT POLYMORPHIC)**

Elemen LHP:

- `text` Summary pemeriksaan
- `nip_pemeriksa`
- `nama_pemeriksa`
- waktu (otomatis)
- morph `Inspectable`

**Comment by bowvernon110391** [comment]
LHP relations:
- [ ] `Inspectable` : dokumen master
- [ ] `Lampiran` : lampiran terkait lhp

**Comment by bcsoetta** [comment]
LHP harus mengait ke IP (Instruksi Pemeriksaan), karena pemeriksa hanya bergerak berdasarkan instruksi.

buat `TraitInstructable`, yang isinya:

- `LHP` -> has one through `InstruksiPemeriksaan`
- `InstruksiPemeriksaan` -> all `Instructable` has one

**Comment by bowvernon110391** [comment]
already done. forgot to close this issue
