### ISSUE TITLE
design logging system

### ISSUE THREAD

**Issue by mehuliate** [bcsoetta/apishinta#6]

**Comment by bowvernon110391** [comment]
cmn aktifitas yg perlu dilog aja, macem input/update/delete data. utk data di api endpoints yg terbuka (gk perlu otorisasi), ya ga usah. gk worth it.

**Comment by bcsoetta** [comment]
Logging sudah diimplementasikan, dengan sistem sbb:

- ada 3 mode, `info`, `warning`, dan `error`
- tiap log bisa dikaitkan dengan object terkait. **Cons: ** makan space karena object terkait diconvert jadi json object dan disimpan, (HINT: harus dibuat opsional).
- untuk mengaitkan aktifitas log dengan user terkait, bisa gunakan `Request::userInfo` (dengan syarat, end point api dikasih guard, jadi `userInfo` tidak tersedia di endpoint yang bebas
