### ISSUE TITLE
design api: plan endpoints

### ISSUE THREAD

**Issue by mehuliate** [bcsoetta/apishinta#7]

**Comment by bowvernon110391** [comment]
Tahap awal adalah pembuatan struktur di kode untuk memfasilitasi pembuatan api endpoints. Sudah dibuatkan beberapa struktur sbb:

1. `ApiController` base class untuk Controller Api lainnya
2. tiap resource yang dimunculkan di api harus memiliki `Transformer` class untuk mengkonversi data internal laravel Eloquent ke data output (JSON). Simple, lihat contoh yang simple dari kelas `KursTransformer`, `PenumpangTransformer`, dan yang agak sedikit kompleks `CDTransformer`
3. untuk data yang bisa diquery, gunakan pagination
4. pagination sudah terintegrasi dengan paginator bawaan laravel (YAAAAY!)
5. untuk data tunggal atau data majemuk yang tidak perlu pagination, tdk perlu pagination
6. data kembalian dari API bisa memunculkan relasi secara opsional (thanks to **Fractal**)
7. API harus mengikuti standar **HATEOAS**, simple, cukup tambahkan property `links` yang berisi URI ke data-data terkait

Sejauh ini sudah dibuat API (belum komplit) untuk /kurs dan /dokumens/cds, walaupun belum semua fiturnya terimplementasi. Bisa dilihat di 28fa942

**Comment by bowvernon110391** [comment]
liat issue #7 utk perkembangan selanjutny
