### ISSUE TITLE
integration with SSO

### ISSUE THREAD

**Issue by mehuliate** [bcsoetta/apishinta#9]

**Comment by bowvernon110391** [comment]
utk development udh ad mockupny jd seolah kita konek ke sso. ada 2 mockup token, `token_pdtt` dan `token_admin`. bisa dpake utk testing api call

**Comment by bcsoetta** [comment]
Integrasi sudah diimplementasikan. Untuk mode `development` bisa disetel token yang digunakan, untuk mode `production` merujuk ke token cookie yang tersimpan di browser
